# Generated by Django 4.0.2 on 2022-03-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hvaccontroller',
            old_name='day_night',
            new_name='night_day',
        ),
    ]
