# Generated by Django 4.0.2 on 2022-03-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_rename_day_night_hvaccontroller_night_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementbool',
            name='measurement_type',
            field=models.CharField(choices=[('temp_heat_output', 'Temp Heat Output'), ('temp_cooling_output', 'Temp Cooling Output'), ('humidifier_output', 'Hum Output'), ('dehumidifier_output', 'Dehum Output')], max_length=25),
        ),
        migrations.AlterField(
            model_name='measurementfloat',
            name='measurement_type',
            field=models.CharField(choices=[('temp', 'Temp'), ('temp_p_response', 'Temp P Response'), ('temp_i_response', 'Temp I Response'), ('temp_d_response', 'Temp D Response'), ('temp_pid_output', 'Temp Pid Output'), ('temp_heat_time_on', 'Temp Heat Time On'), ('temp_heat_time_off', 'Temp Heat Time Off'), ('hum', 'Hum'), ('hum_p_response', 'Hum P Response'), ('hum_i_response', 'Hum I Response'), ('hum_d_response', 'Hum D Response'), ('hum_pid_output', 'Hum Pid Output'), ('hum_heat_time_on', 'Hum Heat Time On'), ('hum_heat_time_off', 'Hum Heat Time Off'), ('error_temp', 'Error Temp'), ('error_hum', 'Error Hum')], max_length=25),
        ),
    ]
