# Generated by Django 4.0.2 on 2022-03-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0003_alter_measurementbool_measurement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementfloat',
            name='measurement_type',
            field=models.CharField(choices=[('temp', 'Temp'), ('temp_pid_error', 'Temp Pid Error'), ('temp_p_response', 'Temp P Response'), ('temp_i_response', 'Temp I Response'), ('temp_d_response', 'Temp D Response'), ('temp_pid_output', 'Temp Pid Output'), ('temp_heat_time_on', 'Temp Heat Time On'), ('temp_heat_time_off', 'Temp Heat Time Off'), ('hum', 'Hum'), ('hum_pid_error', 'Hum Pid Error'), ('hum_p_response', 'Hum P Response'), ('hum_i_response', 'Hum I Response'), ('hum_d_response', 'Hum D Response'), ('hum_pid_output', 'Hum Pid Output'), ('hum_heat_time_on', 'Hum Heat Time On'), ('hum_heat_time_off', 'Hum Heat Time Off'), ('error_temp', 'Error Temp'), ('error_hum', 'Error Hum')], max_length=25),
        ),
    ]
