# Generated by Django 4.0.2 on 2022-03-04 10:44

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0004_alter_measurementfloat_measurement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime.now)),
                ('measurement_type', models.CharField(choices=[('next_compute_period', 'Next Compute Period')], max_length=25)),
                ('value', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intmeasurements', to='sensor_data.hvaccontroller')),
            ],
        ),
    ]
