# Generated by Django 4.0.2 on 2022-03-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0005_measurementint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hvaccontroller',
            name='hum_d',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='hum_i',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='hum_p',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='night_day',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='night_finish_hour',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='night_finish_minute',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='night_start_hour',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='night_start_minute',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='software_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='target_hum',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='target_temp',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='temp_d',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='temp_i',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='temp_p',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='time_period',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
