# Generated by Django 4.0.2 on 2022-03-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0006_alter_hvaccontroller_hum_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hvaccontroller',
            name='host_name',
            field=models.CharField(blank=True, help_text='Mqtt host', max_length=50),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
