# Generated by Django 4.0.3 on 2022-03-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0007_alter_hvaccontroller_host_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hvaccontroller',
            name='time_period',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
