# Generated by Django 4.0.3 on 2022-03-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0008_alter_hvaccontroller_time_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='hvaccontroller',
            name='standby',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hvaccontroller',
            name='night_day',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
