# Generated by Django 4.0.3 on 2022-03-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0009_hvaccontroller_standby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hvaccontroller',
            name='night_target_hum',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hvaccontroller',
            name='night_target_temp',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
