# Generated by Django 4.0.3 on 2022-04-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0010_hvaccontroller_night_target_hum_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='measurementfloat',
            index=models.Index(fields=['time_stamp'], name='time_stamp_index'),
        ),
    ]
