# Generated by Django 4.0.3 on 2022-05-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0011_measurement_float_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='hvaccontroller',
            name='daylight_saving',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
