# Generated by Django 3.2.13 on 2022-07-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0012_hvaccontroller_daylight_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='hvaccontroller',
            name='skins',
            field=models.BooleanField(default=False),
        ),
    ]
